-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Market Data"
(
    table_id integer NOT NULL,
    state character varying COLLATE pg_catalog."default",
    state_code character varying(2) COLLATE pg_catalog."default",
    property_type character varying COLLATE pg_catalog."default",
    property_type_id integer,
    median_sale_price numeric,
    median_list_price numeric,
    median_ppsf integer,
    median_list_ppsf integer,
    homes_sold integer,
    pending_sales integer,
    new_listings integer,
    inventory integer,
    months_of_supply numeric,
    avg_sale_to_list numeric,
    sold_above_list numeric,
    parent_metro_region character varying COLLATE pg_catalog."default",
    year integer,
    month integer,
    rei_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    CONSTRAINT "Market_Data_pkey" PRIMARY KEY (rei_id)
);
END;